# Cloudflare Pages Configuration
name = "arabic-web-express"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"

# Pages configuration
pages_build_output_dir = "dist/public"

# Environment variables
[env.production]
vars = { NODE_ENV = "production" }

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "licenses_db"
database_id = "dcb78a60-f5c3-499b-9d04-d04e59e2dc3c"

