# Cloudflare Pages Configuration
name = "arabic-web-express"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "./"

# Pages configuration
pages_build_output_dir = "dist/public"

# Environment variables
[env.production]
vars = { NODE_ENV = "production" }

